=== redlizard/sqeeze-kde3/packages/kde3-kdegraphics-3.5.9/kpovmodeler/pminsertrules.dtd
<!-- Simple dtd for kpovmodeler insert rules
 Autor: Andreas Zehender <zehender@kde.org> -->

<!-- Validation command for xemacs:
 nsgmls -sv /usr/doc/jade-1.2.1/pubtext/xml.dcl <file> -->

<!-- The root element. -->
<!ELEMENT insertrules (definegroup*, targetclass+)>
<!ATTLIST insertrules
  format CDATA #REQUIRED
>

<!-- Groups together a list of classes. Groups can be nested. -->
<!ELEMENT definegroup ((class | group)+)>
<!ATTLIST definegroup
  name CDATA #REQUIRED
>

<!-- Reference to an object class. -->
<!ELEMENT class EMPTY>
<!ATTLIST class
  name CDATA #REQUIRED
>

<!-- Reference to a defined group. -->
<!ELEMENT group EMPTY>
<!ATTLIST group
  name CDATA #REQUIRED
>

<!-- Contains the insert rules for one class
 (the class where the new object is inserted) -->
<!ELEMENT targetclass (definegroup*, rule+)>
<!ATTLIST targetclass
  name CDATA #REQUIRED
>

<!-- One rule for the current class.
 Insert a list of groups and classes (the object classes that can be inserted)
 and one condition. If the condition is omitted,
 the classes can allways be inserted. --> 
<!ELEMENT rule ((group | class)+, (and | or | not | before | after | contains
                                   | greater | less | equal)?)>

<!-- Simple negation. Insert one condition -->
<!ELEMENT not (and | or | before | after | contains | greater | less | equal)>

<!-- Logical and. Insert any number of conditions -->
<!ELEMENT and (and | or | not | before | after | contains | greater | less | equal)+>

<!-- Logical or. Insert any number of conditions -->
<!ELEMENT or (and | or | not | before | after | contains | greater | less | equal)+>

<!-- Condition. Value is true if the object already contains
 objects of the given class or group before the insert point. -->
<!ELEMENT before (class | group)>

<!-- Condition. Value is true if the object already contains
 objects of the given class or group after the insert point. -->
<!ELEMENT after (class | group)>

<!-- Condition. Value is true if the two values (child xml tags)
 are equal. -->
<!ELEMENT equal ((property | count | const), (property | count | const))>

<!-- Condition. Value is true if the first value (child xml tag)
 is greater than the second. -->
<!ELEMENT greater ((property | count | const), (property | count | const))>

<!-- Condition. Value is true if the first value (child xml tag)
 is less than the second. -->
<!ELEMENT less ((property | count | const), (property | count | const))>

<!-- Condition. Value is true if the object contains
 objects of the given classes and groups. -->
<!ELEMENT contains (group | class)+>


<!-- Value. Value is the class property of the object, where the 
 new object should be inserted into. -->
<!ELEMENT property EMPTY>
<!ATTLIST property
  name CDATA #REQUIRED
>

<!-- Value. Defines a constant (number or string). -->
<!ELEMENT const EMPTY>
<!ATTLIST const
  value CDATA #REQUIRED
>

<!-- Value. Counts the number of already inserted instances of the given
 groups or classes. -->
<!ELEMENT count (group | class)+>

=== redlizard/sqeeze-kde3/packages/kde3-kdegraphics-3.5.9/kpovmodeler/baseinsertrules.xml
<!DOCTYPE insertrules SYSTEM "pminsertrules.dtd">
<insertrules format="1.0">

  <definegroup name="Transformations">
    <class name="Translate"/>
    <class name="Scale"/>
    <class name="Rotate"/>
    <class name="PovrayMatrix"/>
  </definegroup>

  <definegroup name="Textures">
    <class name="Pigment"/>
    <class name="Normal"/>
    <class name="Finish"/>
    <class name="Texture"/>
    <class name="InteriorTexture"/>
    <class name="Interior"/>
    <class name="Material"/>
  </definegroup>

  <definegroup name="ObjectModifier">
    <group name="Transformations"/>
    <group name="Textures"/>
    <class name="BoundedBy"/>
    <class name="ClippedBy"/>
    <class name="Photons"/>
  </definegroup>

  <targetclass name="Blob">
    <definegroup name="ObjectModifier">
      <group name="Transformations"/>
      <group name="Textures"/>
    </definegroup>
    <definegroup name="BlobComponents">
      <class name="BlobCylinder"/>
      <class name="BlobSphere"/>
    </definegroup>

    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <group name="ObjectModifier"/>
      <not><before><group name="BlobComponents"/></before></not>
    </rule>
    <rule>
      <group name="BlobComponents"/>
      <not><after><group name="ObjectModifier"/></after></not>
    </rule>
  </targetclass>

  <targetclass name="BlobCylinder">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
      <group name="Transformations"/>
      <class name="Texture"/>
      <class name="InteriorTexture"/>
      <class name="Pigment"/>
      <class name="Normal"/>
      <class name="Finish"/>
    </rule>
  </targetclass>
  <targetclass name="BlobSphere">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
      <group name="Transformations"/>
      <class name="Texture"/>
      <class name="InteriorTexture"/>
      <class name="Pigment"/>
      <class name="Normal"/>
      <class name="Finish"/>
    </rule>
  </targetclass>

  <targetclass name="BoundedBy">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
      <class name="SolidObject"/>
    </rule>
  </targetclass>

  <targetclass name="Camera">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
      <group name="Transformations"/>
      <class name="Normal"/>
    </rule>
  </targetclass>

  <targetclass name="ClippedBy">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
      <class name="SolidObject"/>
    </rule>
  </targetclass>

  <targetclass name="CSG">
    <definegroup name="CSGObjects">
      <class name="GraphicalObject"/>
      <class name="Light"/>
    </definegroup>

    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <group name="ObjectModifier"/>
      <not><before><group name="CSGObjects"/></before></not>
    </rule>
    <rule>
      <group name="CSGObjects"/>
      <not><after><group name="ObjectModifier"/></after></not>
    </rule>
  </targetclass>

  <targetclass name="LightGroup">
    <definegroup name="LightGroupObjects">
      <class name="GraphicalObject"/>
      <class name="Light"/>
    </definegroup>

    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <group name="ObjectModifier"/>
      <not><before><group name="LightGroupObjects"/></before></not>
    </rule>
    <rule>
      <group name="LightGroupObjects"/>
      <not><after><group name="ObjectModifier"/></after></not>
    </rule>
  </targetclass>

  <targetclass name="Mesh">
    <definegroup name="MeshObjects">
      <class name="Triangle"/>
    </definegroup>

    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <group name="ObjectModifier"/>
      <not><before><group name="MeshObjects"/></before></not>
    </rule>
    <rule>
      <group name="MeshObjects"/>
      <not><after><group name="ObjectModifier"/></after></not>
    </rule>
  </targetclass>

  <targetclass name="Triangle">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <group name="ObjectModifier"/>
      <not><parent><class name="Mesh"/></parent></not>
    </rule>
  </targetclass>

  <targetclass name="Declare">
    <rule>
      <class name="GraphicalObject"/>
      <class name="Light"/>
      <class name="TextureBase"/>
      <equal>
        <property name="numberOfChildren"/>
        <const value="0"/>
      </equal>
    </rule>
    <rule>
      <class name="Texture"/>
      <contains><class name="Texture"/></contains>
    </rule>
    <rule>
      <class name="InteriorTexture"/>
      <contains><class name="InteriorTexture"/></contains>
    </rule>
  </targetclass>

  <targetclass name="Density">
    <definegroup name="ListPattern">
      <class name="ColorList"/>
      <class name="DensityList"/>
    </definegroup>
    <definegroup name="Map">
      <class name="ColorMap"/>
      <class name="DensityMap"/>
    </definegroup>
    <definegroup name="Sum">
      <class name="Pattern"/>
      <group name="Map"/>
      <class name="Warp"/>
      <class name="SolidColor"/>
      <group name="ListPattern"/>
    </definegroup>

    <rule>
      <class name="SolidColor"/>
      <class name="ColorList"/>
      <class name="DensityList"/>
      <not><contains><group name="Sum"/></contains></not>
    </rule>
    <rule>
      <class name="Pattern"/>
      <and>
        <not>
          <contains>
            <class name="Pattern"/>
            <group name="ListPattern"/>
          </contains>
        </not>
        <not><after><group name="Map"/></after></not>
        <not><after><class name="Warp"/></after></not>
        <not><after><class name="BlendMapModifiers"/></after></not>
        <not><after><group name="Transformations"/></after></not>
      </and>
    </rule>
    <rule>
      <class name="Warp"/>
      <after><class name="Pattern"/></after>
    </rule>
    <rule>
      <group name="Map"/>
      <and>
        <not>
          <contains>
            <group name="Map"/>
            <group name="ListPattern"/>
            <class name="SolidColor"/>
          </contains>
        </not>
        <not><before><class name="Pattern"/></before></not>
      </and>
    </rule>
    <rule>
      <class name="QuickColor"/>
      <group name="Transformations"/>
      <not><before><class name="Pattern"/></before></not>
    </rule>
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
  </targetclass>

  <targetclass name="Finish">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
  </targetclass>

  <targetclass name="Fog">
    <rule>
      <group name="Transformations"/>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
  </targetclass>

  <targetclass name="GraphicalObject">
    <exception class="CSG"/>
    <exception class="Mesh"/>
    <rule>
      <group name="ObjectModifier"/>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
  </targetclass>

  <targetclass name="Interior">
    <rule>
      <class name="Media"/>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
  </targetclass>

  <targetclass name="Light">
    <rule>
      <group name="Transformations"/>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <class name="LooksLike"/>
      <not><contains><class name="LooksLike"/></contains></not>
    </rule>
    <rule>
      <class name="ProjectedThrough"/>
      <not><contains><class name="ProjectedThrough"/></contains></not>
    </rule>
    <rule>
      <class name="Photons"/>
      <not><contains><class name="Photons"/></contains></not>
    </rule>
  </targetclass>

  <targetclass name="ColorList">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <class name="SolidColor"/>
      <or>
        <and>
          <equal><property name="listType"/><const value="Hexagon"/></equal>
          <less><count><class name="SolidColor"/></count><const value="3"/></less>
        </and>
        <and>
          <not><equal><property name="listType"/><const value="Hexagon"/></equal></not>
          <less><count><class name="SolidColor"/></count><const value="2"/></less>
        </and>
      </or>
    </rule>
  </targetclass>

  <targetclass name="DensityList">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <class name="Density"/>
      <or>
        <and>
          <equal><property name="listType"/><const value="Hexagon"/></equal>
          <less><count><class name="Density"/></count><const value="3"/></less>
        </and>
        <and>
          <not><equal><property name="listType"/><const value="Hexagon"/></equal></not>
          <less><count><class name="Density"/></count><const value="2"/></less>
        </and>
      </or>
    </rule>
  </targetclass>

  <targetclass name="NormalList">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <class name="Normal"/>
      <and>
        <equal><property name="depth"/><const value="0.0"/></equal>
        <or>
          <and>
            <equal><property name="listType"/><const value="Hexagon"/></equal>
            <less><count><class name="Normal"/></count><const value="3"/></less>
          </and>
          <and>
            <not><equal><property name="listType"/><const value="Hexagon"/></equal></not>
            <less><count><class name="Normal"/></count><const value="2"/></less>
          </and>
        </or>
      </and>
    </rule>
  </targetclass>

  <targetclass name="PigmentList">
    <rule>
      <class name="Comment"/>
      <class name="Raw"/>
    </rule>
    <rule>
      <class name="Pigment"/>
      <or>
        <and>
          <equal><property name="listType"/><const value="Hexagon"/></equal>
          <less><count><class name="Pigment"/></count><const value="3"/></less>
        </and>
        <and>
